version: '2.4'
services:
    web:
        build: .
        command: node server.js
        volumes: 
            - ./app:/app
        ports:
            - ${API_PORT}:3300
        restart: on-failure
        depends_on: 
            - mongodb
    
    mongodb:
        image: mongo
        ports:
            - ${MONGO_PORT}:27017
        restart: always
        environment: 
            - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME}
            - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
        command: mongod --auth --logpath=/dev/null
