version: "2.4"
services:
  web:
    extends:
      file: common-services.yml
      service: base_node
    command: npm start
    ports:
      - ${API_PORT}:3300
    restart: on-failure
  mongodb:
    image: mongo
    ports:
      - ${MONGO_PORT}:27017
    restart: always  
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
  rabbitmq:
    image: rabbitmq:3.8.0-management
    hostname: crawlers-rabbitmq
    ports:
      - 1${RABBITMQ_PORT}:15672
      - ${RABBITMQ_PORT}:5672
    expose:
      - 1${RABBITMQ_PORT}
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USERNAME}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
  nginx:
    image: nginx:1.17.3
    ports:
      - ${NGINX_PORT}:80
    volumes:
      - ./app:/usr/share/nginx/html:ro
    restart: always
  enfileirador:
    extends:
      file: common-services.yml
      service: base_node
    command: node workers/enfileirador.js
  worker-jte-sp-2:
    extends:
      file: common-services.yml
      service: base_node
    mem_limit: ${PUPPETEER_MEMORIA_MAX}
    mem_reservation: ${PUPPETEER_MEMORIA_MIN}
    command: node workers/JTE/extracaoNovos_Sp_2.js
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
  worker-jte-sp-15:
    extends:
      file: common-services.yml
      service: base_node
    mem_limit: ${PUPPETEER_MEMORIA_MAX}
    mem_reservation: ${PUPPETEER_MEMORIA_MIN}
    command: node workers/JTE/extracaoNovos_Sp_15.js
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
  worker-jte-rj:
    extends:
      file: common-services.yml
      service: base_node
    mem_limit: ${PUPPETEER_MEMORIA_MAX}
    mem_reservation: ${PUPPETEER_MEMORIA_MIN}
    command: node workers/JTE/extracaoNovos_Rj.js
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
  worker-jte-mg:
    extends:
      file: common-services.yml
      service: base_node
    mem_limit: ${PUPPETEER_MEMORIA_MAX}
    mem_reservation: ${PUPPETEER_MEMORIA_MIN}
    command: node workers/JTE/extracaoNovos_Mg.js
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
  # geraFila:
  #     extends:
  #       file: common-services.yml
  #       service: base_node
  #     mem_limit: ${PUPPETEER_MEMORIA_MAX}
  #     mem_reservation: ${PUPPETEER_MEMORIA_MIN}
  #     command: node workers/JTE/extracaoNovos_Mg.js
  #     logging:
  #       driver: "json-file"
  #       options:
  #         max-size: "10m"
  #         max-file: "5"

