version: "2.4"
services:
  web:
    extends:
      file: common-services.yml
      service: base_node
    command: npm start
    ports:
      - ${API_PORT}:3300
    restart: on-failure

  # mongodb:
  #   image: mongo
  #   ports:
  #     - ${MONGO_PORT}:27017
  #   volumes:
  #     - ./mongodb:/data/db
  #     - ./backups:/backups
  #   restart: always
  #   environment:
  #     - MONGO_DATA_DIR=/data/db
  #     - MONGO_LOG_DIR=/dev/null
  #     - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME}
  #     - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
  #   command: mongod --auth --logpath=/dev/null

  # rabbitmq:
  #   image: rabbitmq:3.8.0-management
  #   hostname: crawlers-rabbitmq
  #   ports:
  #     - 1${RABBITMQ_PORT}:15672
  #     - ${RABBITMQ_PORT}:5672
  #   restart: always
  #   environment:
  #     - RABBITMQ_DEFAULT_USER=${RABBITMQ_USERNAME}
  #     - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}

  nginx:
    image: nginx:1.17.3
    ports:
      - ${NGINX_PORT}:80
    volumes:
      - ./app:/usr/share/nginx/html:ro
    restart: always

  enfileirador:
    extends:
      file: common-services.yml
      service: base_node
    command: node workers/enfileirador.js

  worker-tjba-portal:
    extends:
      file: common-services.yml
      service: base_node
    command: node workers/TJBAPortal/extracaoNovos.js

  worker-tjsp-oab:
    extends:
      file: common-services.yml
      service: base_node
    command: node workers/TJSP/extracao.js

  worker-tjmg-oab:
    extends:
      file: common-services.yml
      service: base_node
    depends_on:
      - nginx
      - mongodb
    command: node workers/TJMG/extracaoNovos.js

  cadastro-consulta:
    extends: 
      file: common-services.yml
      service: base_node
    command: node workers/consumer_cadastro_consulta.js
