version: "2.4"
services:
  web:
    extends:
      file: common-services.yml
      service: base_node
    command: npm start
    ports:
      - ${API_PORT}:3300
    restart: on-failure
  # mongodb:
  #   image: mongo
  #   ports:
  #     - ${MONGO_PORT}:27017
  #   restart: always  
  #   environment:
  #     - MONGO_DATA_DIR=/data/db
  #     - MONGO_LOG_DIR=/dev/null
  #     - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME}
  #     - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
  # rabbitmq:
  #   image: rabbitmq:3.8.0-management
  #   hostname: crawlers-rabbitmq
  #   ports:
  #     - 1${RABBITMQ_PORT}:15672
  #     - ${RABBITMQ_PORT}:5672
  #   expose:
  #     - 1${RABBITMQ_PORT}
  #   restart: always
  #   environment:
  #     - RABBITMQ_DEFAULT_USER=${RABBITMQ_USERNAME}
  #     - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
  nginx:
    image: nginx:1.17.3
    ports:
      - ${NGINX_PORT}:80
    volumes:
      - ./app:/usr/share/nginx/html:ro
    restart: always
  enfileirador:
    extends:
      file: common-services.yml
      service: base_node
    command: node workers/enfileirador.js
  # worker-jte-sp-2:
  #   extends:
  #     file: common-services.yml
  #     service: base_node
  #   mem_limit: ${PUPPETEER_MEMORIA_MAX}
  #   mem_reservation: ${PUPPETEER_MEMORIA_MIN}
  #   command: node workers/JTE/extracaoNovos_Sp_2.js
  #   restart: always
  #   logging:
  #     driver: "json-file"
  #     options:
  #       max-size: "10m"
  #       max-file: "5"
  # worker-jte-sp-15:
  #   extends:
  #     file: common-services.yml
  #     service: base_node
  #   mem_limit: ${PUPPETEER_MEMORIA_MAX}
  #   mem_reservation: ${PUPPETEER_MEMORIA_MIN}
  #   command: node workers/JTE/extracaoNovos_Sp_15.js
  #   restart: always
  #   logging:
  #     driver: "json-file"
  #     options:
  #       max-size: "10m"
  #       max-file: "5"
  # worker-jte-ba:
  #   extends:
  #     file: common-services.yml
  #     service: base_node
  #   mem_limit: ${PUPPETEER_MEMORIA_MAX}
  #   mem_reservation: ${PUPPETEER_MEMORIA_MIN}
  #   command: node workers/JTE/extracaoNovos_Ba.js
  #   logging:
  #     driver: "json-file"
  #     options:
  #       max-size: "10m"
  #       max-file: "5"
  # worker-jte-mg:
  #   extends:
  #     file: common-services.yml
  #     service: base_node
  #   mem_limit: ${PUPPETEER_MEMORIA_MAX}
  #   mem_reservation: ${PUPPETEER_MEMORIA_MIN}
  #   command: node workers/JTE/extracaoNovos_Mg.js
  #   logging:
  #     driver: "json-file"
  #     options:
  #       max-size: "10m"
  #       max-file: "5"
  # worker-tjsp-processo:
  #   extends:
  #     file: common-services.yml
  #     service: base_node
  #   command: node workers/TJSP/extracaoProcesso.js

  # worker-tjsc-oab:
  #   extends:
  #     file: common-services.yml
  #     service: base_node
  #   command: node workers/TJSC/extracaoNovos.js

  # worker-tjsc-processo:
  #   extends:
  #     file: common-services.yml
  #     service: base_node
  #   command: node workers/TJSC/extracaoProcesso.js

  # worker-tjmg-oab:
  #   extends:
  #     file: common-services.yml
  #     service: base_node
  #   command: node workers/TJMG/extracaoNovos.js

  # cadastro-consulta:
  #   extends:
  #     file: common-services.yml
  #     service: base_node
  #   command: node workers/consumer_cadastro_consulta.js

  # novos-processos-jte-sp-2:
  #   extends:
  #     file: common-services.yml
  #     service: base_node
  #   command: node workers/JTE/criaFilaNovos_SP_2
  #   restart: always
  #   logging:
  #     driver: "json-file"
  #     options:
  #       max-size: "5m"
  #       max-file: "2"
  
  # novos-processos-jte-sp-15:
  #   extends:
  #     file: common-services.yml
  #     service: base_node
  #   command: node workers/JTE/criaFilaNovos_SP_15
  #   restart: always
  #   logging:
  #     driver: "json-file"
  #     options:
  #       max-size: "5m"
  #       max-file: "2"
      
  
  
  worker-tjba-portal:
    extends:
      file: common-services.yml
      service: base_node
    command: node workers/TJBAPortal/extracaoNovos.js

  worker-tjsp-oab:
    extends:
      file: common-services.yml
      service: base_node
    command: node workers/TJSP/extracao.js

  worker-tjsp-processo:
    extends:
      file: common-services.yml
      service: base_node
    command: node workers/TJSP/extracaoProcesso.js

  worker-tjsp-peticao:
    extends:
      file: common-services.yml
      service: base_node
    command: node workers/TJSP/extracaoPeticao.js

  worker-tjsc-oab:
    extends:
      file: common-services.yml
      service: base_node
    command: node workers/TJSC/extracaoNovos.js

  worker-tjsc-processo:
    extends:
      file: common-services.yml
      service: base_node
    command: node workers/TJSC/extracaoProcesso.js

  novos-processos-jte:
    extends:
      file: common-services.yml
      service: base_node
    command: pm2 start workers/JTE/criaFilaNovosPrincipais01.js --no-daemon
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "2"

  novos-processos-jte-2:
    extends:
      file: common-services.yml
      service: base_node
    command: pm2 start workers/JTE/criaFilaNovosSecundario.js --no-daemon
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "2"

  novos-processos-jte-3:
    extends:
      file: common-services.yml
      service: base_node
    command: pm2 start workers/JTE/criaFilaNovosTodosEstados.js --no-daemon
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "2"

  novos-processos-jte-all:
    extends:
      file: common-services.yml
      service: base_node
    command: pm2 start workers/JTE/criaFilaNovosTodosEstados.js --no-daemon
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "2"

  worker-jte-01:
    extends:
      file: common-services.yml
      service: base_node
    mem_limit: ${PUPPETEER_MEMORIA_MAX}
    mem_reservation: ${PUPPETEER_MEMORIA_MIN}
    command: pm2 start workers/JTE/processDocker01.yml --no-daemon
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

  worker-jte-02:
    extends:
      file: common-services.yml
      service: base_node
    mem_limit: ${PUPPETEER_MEMORIA_MAX}
    mem_reservation: ${PUPPETEER_MEMORIA_MIN}
    command: pm2 start workers/JTE/processDocker01.yml --no-daemon
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

  worker-jte-03:
    extends:
      file: common-services.yml
      service: base_node
    mem_limit: ${PUPPETEER_MEMORIA_MAX}
    mem_reservation: ${PUPPETEER_MEMORIA_MIN}
    command: pm2 start workers/JTE/processDocker02.yml --no-daemon
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

  worker-jte-04:
    extends:
      file: common-services.yml
      service: base_node
    mem_limit: ${PUPPETEER_MEMORIA_MAX}
    mem_reservation: ${PUPPETEER_MEMORIA_MIN}
    command: pm2 start workers/JTE/processDocker02.yml --no-daemon
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

  worker-jte-05:
    extends:
      file: common-services.yml
      service: base_node
    mem_limit: ${PUPPETEER_MEMORIA_MAX}
    mem_reservation: ${PUPPETEER_MEMORIA_MIN}
    command: pm2 start workers/JTE/processDocker03.yml --no-daemon
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

  worker-jte-06:
    extends:
      file: common-services.yml
      service: base_node
    mem_limit: ${PUPPETEER_MEMORIA_MAX}
    mem_reservation: ${PUPPETEER_MEMORIA_MIN}
    command: pm2 start workers/JTE/processDocker03.yml --no-daemon
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

  # worker-jte-07:
  #   extends:
  #     file: common-services.yml
  #     service: base_node
  #   mem_limit: ${PUPPETEER_MEMORIA_MAX}
  #   mem_reservation: ${PUPPETEER_MEMORIA_MIN}
  #   command: pm2 start process.yml --no-daemon
  #   restart: always
  #   logging:
  #     driver: "json-file"
  #     options:
  #       max-size: "10m"
  #       max-file: "5"

  # worker-jte-08:
  #   extends:
  #     file: common-services.yml
  #     service: base_node
  #   mem_limit: ${PUPPETEER_MEMORIA_MAX}
  #   mem_reservation: ${PUPPETEER_MEMORIA_MIN}
  #   command: pm2 start process.yml --no-daemon
  #   restart: always
  #   logging:
  #     driver: "json-file"
  #     options:
  #       max-size: "5m"
  #       max-file: "2"

  # worker-jte-09:
  #   extends:
  #     file: common-services.yml
  #     service: base_node
  #   mem_limit: ${PUPPETEER_MEMORIA_MAX}
  #   mem_reservation: ${PUPPETEER_MEMORIA_MIN}
  #   command: pm2 start process.yml --no-daemon
  #   restart: always
  #   logging:
  #     driver: "json-file"
  #     options:
  #       max-size: "5m"
  #       max-file: "2"

  # worker-jte-10:
  #   extends:
  #     file: common-services.yml
  #     service: base_node
  #   mem_limit: ${PUPPETEER_MEMORIA_MAX}
  #   mem_reservation: ${PUPPETEER_MEMORIA_MIN}
  #   command: pm2 start process.yml --no-daemon
  #   restart: always
  #   logging:
  #     driver: "json-file"
  #     options:
  #       max-size: "5m"
  #       max-file: "2"

  # worker-jte-11:
  #   extends:
  #     file: common-services.yml
  #     service: base_node
  #   mem_limit: ${PUPPETEER_MEMORIA_MAX}
  #   mem_reservation: ${PUPPETEER_MEMORIA_MIN}
  #   command: pm2 start process.yml --no-daemon
  #   restart: always
  #   logging:
  #     driver: "json-file"
  #     options:
  #       max-size: "5m"
  #       max-file: "2"

  # worker-jte-12:
  #   extends:
  #     file: common-services.yml
  #     service: base_node
  #   mem_limit: ${PUPPETEER_MEMORIA_MAX}
  #   mem_reservation: ${PUPPETEER_MEMORIA_MIN}
  #   command: pm2 start process.yml --no-daemon
  #   restart: always
  #   logging:
  #     driver: "json-file"
  #     options:
  #       max-size: "5m"
  #       max-file: "2"
