const { PeticaoTJRS1 } = require('../extratores/PeticaoTJRS1');
const { OabTJRS } = require('../extratores/OabTJRS')
const Comarca = require('../models/schemas/comarcas');
require('../bootstrap');


const main =() => {
  // let extrator = new PeticaoTJRS1();

  // let extrator = new OabTJRS('https://www.tjrs.jus.br/site_php/consulta/index.php', false)
  // extrator.extrair("71775RS", "5fb6a87a9f0dbd915a12b0bc", 1).then(res => console.log(res));

  // extrator.extrair('5018418-72.2019.8.21.0001').then(resp => console.log(resp));

  // let comarca = new Comarca({Estado: 'RS', Comarca: '000', Nome: 'teste', Tribunal: 21, Orgao: 8, Metadados: {slang: 'comarca_code', outro: 'outro'}});
  // comarca.salvar().then(e => console.log(e));

  let feitos = Object.keys(comarcasCode).map(codigo => {
    let comarca_obj = {
      Estado: 'CE',
      Comarca: codigo,
      Nome: comarcasCode[codigo].nome,
      Tribunal: 6,
      Orgao: 8,
      // Metadados: {
      //   tjrs_select_id: comarcasCode[codigo].id
      // },
      // UltimoProcesso: ultimosProcessos[Number(codigo)]
    }

    // if (ultimosProcessos[Number(codigo)])
      new Comarca(comarca_obj).salvar().then(e => console.log(`${codigo} -> ${ultimosProcessos[Number(codigo)]}`))
  })

  console.log(feitos.filter(e => e).length)
}

const comarcasCode = {
  "0": {nome: "Tribunal de Justiça"},
  "1": {nome: "FORTALEZA"},
  "2": {nome: "FORTALEZA"},
  "3": {nome: "FORTALEZA"},
  "4": {nome: "FORTALEZA"},
  "5": {nome: "FORTALEZA"},
  "6": {nome: "FORTALEZA"},
  "7": {nome: "FORTALEZA"},
  "8": {nome: "FORTALEZA"},
  "9": {nome: "FORTALEZA"},
  "10": {nome: "FORTALEZA"},
  "11": {nome: "FORTALEZA"},
  "12": {nome: "FORTALEZA"},
  "13": {nome: "FORTALEZA"},
  "14": {nome: "FORTALEZA"},
  "15": {nome: "FORTALEZA"},
  "16": {nome: "FORTALEZA"},
  "17": {nome: "FORTALEZA"},
  "18": {nome: "FORTALEZA"},
  "19": {nome: "FORTALEZA"},
  "20": {nome: "FORTALEZA"},
  "21": {nome: "FORTALEZA"},
  "22": {nome: "FORTALEZA"},
  "23": {nome: "FORTALEZA"},
  "24": {nome: "FORTALEZA"},
  "25": {nome: "FORTALEZA"},
  "26": {nome: "Corregedoria Geral de Justiça"},
  "27": {nome: "ACARAPE"},
  "28": {nome: "ACARÁU"},
  "29": {nome: "ACOPIARA"},
  "30": {nome: "AIUABA"},
  "31": {nome: "ALTO SANTO"},
  "32": {nome: "AMONTADA"},
  "33": {nome: "ANTONINA DO NORTE"},
  "34": {nome: "AQUIRAZ"},
  "35": {nome: "ARACATI"},
  "75": {nome: "EUSÉBIO"},
  "76": {nome: "FARIAS BRITO"},
  "77": {nome: "FORQUILHA"},
  "78": {nome: "FORTIM"},
  "79": {nome: "FRENCHEIRINHA"},
  "80": {nome: "GRAÇA"},
  "81": {nome: "GRANJA"},
  "82": {nome: "GROAIRAS"},
  "83": {nome: "GUAIUBA"},
  "84": {nome: "GUARACIABA DO NORTE"},
  "85": {nome: "HIDÔLANDIA"},
  "86": {nome: "HORIZONTE"},
  "87": {nome: "IBIAPINA"},
  "88": {nome: "IBICUITINGA"},
  "89": {nome: "ICAPUÍ"},
  "90": {nome: "ICÓ"},
  "91": {nome: "IGUATU"},
  "92": {nome: "INDEPENDÊNCIA"},
  "93": {nome: "IPAPORANGA"},
  "94": {nome: "IPAUMIRIM"},
  "95": {nome: "IPU"},
  "96": {nome: "IPUEIRAS"},
  "97": {nome: "IRACEMA"},
  "98": {nome: "IRAUÇUBA"},
  "99": {nome: "ITAITINGA"},
  "100": {nome: "TAPAJÉ"},
  "101": {nome: "ITAPIPOCA"},
  "103": {nome: "ITAPIÚNA"},
  "104": {nome: "ITAREMA"},
  "105": {nome: "ITATIRA"},
  "106": {nome: "JAGUARETAMA"},
  "107": {nome: "JAGUARIBE"},
  "108": {nome: "JAGUARUANA"},
  "109": {nome: "JARDIM"},
  "110": {nome: "JATI"},
  "111": {nome: "JIJOCA DE JERICOACOARA"},
  "112": {nome: "JUAZEIRO DO NORTE"},
  "113": {nome: "JUCÁS"},
  "114": {nome: "LAVRAS DE MANGABEIRA"},
  "115": {nome: "LIMOEIRO DO NORTE"},
  "116": {nome: "MADALENA"},
  "117": {nome: "MARACANAÚ"},
  "119": {nome: "MARANGUAPE"},
  "120": {nome: "MARCO"},
  "121": {nome: "MASSAPÊ"},
  "122": {nome: "MAURITI"},
  "123": {nome: "MERUOCA"},
  "124": {nome: "MILAGRES"},
  "125": {nome: "MISSÃO VELHA"},
  "126": {nome: "MOMBAÇA"},
  "127": {nome: "MONSENHOR TABOSA"},
  "128": {nome: "MORADA NOVA"},
  "129": {nome: "MORRINHOS"},
  "130": {nome: "MUCAMBO"},
  "131": {nome: "MULUNGU"},
  "132": {nome: "NOVA OLINDA"},
  "133": {nome: "NOVA RUSSAS"},
  "134": {nome: "NOVO ORIENTE"},
  "135": {nome: "ORÓS PACAJUS"},
  "136": {nome: "PACAJUS"},
  "137": {nome: "PACATUBA"},
  "138": {nome: "PACOTI"},
  "139": {nome: "PALMÁCIA"},
  "140": {nome: "PARACURU"},
  "141": {nome: "PARAIPABA"},
  "142": {nome: "PARAMBU"},
  "143": {nome: "PEDRA BRANCA"},
  "144": {nome: "PETENCOSTE"},
  "145": {nome: "PEREIRO"},
  "146": {nome: "PINDORETAMA"},
  "147": {nome: "PIQUET CARNEIRO"},
  "148": {nome: "PORANGA"},
  "149": {nome: "PORTEIRAS"},
  "150": {nome: "QUITERIANÓPOLIS"},
  "151": {nome: "QUIXADÁ"},
  "153": {nome: "QUIXELÔ"},
  "154": {nome: "QUIXERAMOBIM"},
  "155": {nome: "QUIXERÉ"},
  "156": {nome: "REDENÇÃO"},
  "157": {nome: "RERIUTABA"},
  "158": {nome: "RUSSAS"},
  "159": {nome: "SABOEIRO"},
  "160": {nome: "SANTA QUITÉRIA"},
  "161": {nome: "SANTANA DO ACARAÚ"},
  "162": {nome: "SANTANA DO CARIRI"},
  "163": {nome: "SÃO BENEDITO"},
  "164": {nome: "SÃO GONÇALO DO AMARANTE"},
  "165": {nome: "SÃO LUIZ DO CURU"},
  "166": {nome: "SENADOR POMPEU"},
  "167": {nome: "SOBRAL"},
  "168": {nome: "SOLONÓPOLE"},
  "169": {nome: "TABULEIRO DO NORTE"},
  "170": {nome: "TAMBORIL"},
  "171": {nome: "TAUÁ"},
  "173": {nome: "TIANGUÁ"},
  "175": {nome: "TRAIRI"},
  "176": {nome: "UBAJARA"},
  "177": {nome: "UMIRIM"},
  "178": {nome: "RURUBURETAMA"},
  "179": {nome: "URUOCA"},
  "180": {nome: "VARJOTA"},
  "181": {nome: "VÁRZEA ALEGRE"},
  "182": {nome: "VIÇOSA DO CEARÁ"},
  "183": {nome: "ABAIARA"},
  "184": {nome: "ALCÂNTARAS"},
  "185": {nome: "ALTANEIRA"},
  "186": {nome: "APUIARÉS"},
  "187": {nome: "ARNEIÓZ"},
  "188": {nome: "BANABUI"},
  "189": {nome: "CATUNDA"},
  "190": {nome: "CHORÓ LIMÃO"},
  "191": {nome: "DEPUTADO IRAPUAM PINHEIRO"},
  "192": {nome: "ERERÊ"},
  "193": {nome: "GENERAL SAMPAIO"},
  "194": {nome: "GRANJEIRO"},
  "195": {nome: "GUARAMIRANGA"},
  "196": {nome: "IBARETAMA"},
  "197": {nome: "ITAIÇABA"},
  "198": {nome: "JAGUARIBARA"},
  "199": {nome: "MARTINÓPOLE"},
  "200": {nome: "MILHÃ"},
  "201": {nome: "MIRAIMA"},
  "202": {nome: "MORAIJO"},
  "203": {nome: "OCARA"},
  "204": {nome: "PACUKÁ"},
  "205": {nome: "PALHANO"},
  "206": {nome: "PARAMOTI"},
  "207": {nome: "PENAFORTE"},
  "208": {nome: "PIRES FERREIRA"},
  "209": {nome: "POTENGI"},
  "210": {nome: "POTIRETAMA"},
  "211": {nome: "SALITRE"},
  "212": {nome: "SÃO JOÃO DO JAGUARIBE"},
  "213": {nome: "SENADOR SÁ"},
  "214": {nome: "TARRAFAS"},
  "215": {nome: "TEJUÇUOCA"},
  "216": {nome: "TURURU"},
  "217": {nome: "IMARI"},

};

main();

// db.processo.aggregate([
//   {'$match': {
//       'CnjDetalhes.Tribunal': 21,
//       'CnjDetalhes.OrgaoJustica': 8,
//       'CnjDetalhes.Ano': 2020,
//     }},
//   {'$group': {
//       '_id': '$CnjDetalhes.UnidadeOrigem',
//       'NumeroCNJ': {'$max': '$NumeroCNJ'},
//     }},
//   {'$project': {
//       '_id': 0,
//       'Comarca': '$_id',
//       'NumeroCNJ': 1,
//     }},
// ])